AWSTemplateFormatVersion: 2010-09-09
Description: 'Create an RDS Instance'

Resources: 
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: 'db.t3.micro'
      BackupRetentionPeriod: 7
      DBInstanceIdentifier: 'MyNewRDSInstance'
      Engine: 'mysql'
      MasterUsername: 'admin'
      MasterUserPassword: 'password'
    